MMakerBotPanel/Models/TicketList.cs
namespace MMakerBotPanel.Models
{
    public class TicketList
    {
        public int TicketID { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string TicketName { get; set; }
        public string Email { get; set; }
        public string LastActivity { get; set; }
        public TICKETSTATUS TicketStatus { get; set; }
    }
}

MMakerBotPanel/Controllers/TicketController.cs
using MMakerBotPanel.Business;
using MMakerBotPanel.Database.Context;
using MMakerBotPanel.Database.Model;
using MMakerBotPanel.Models;
using MMakerBotPanel.Models.ChatModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI.WebControls;

namespace MMakerBotPanel.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        private readonly ModelContext db = new ModelContext();

        [HttpPost]
        public JsonResult CreateTicket(string TicketName, string TicketMessage)
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                Ticket createTicket = new Ticket();
                int UserID = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                createTicket.UserID = UserID;
                createTicket.LastActivity = DateTime.Now;
                createTicket.CreateDate = DateTime.Now;
                createTicket.TicketName = TicketName;
                createTicket.TicketStatusEnumType = TICKETSTATUS.AwaitingAnswer;
                createTicket.TicketDetails = new List<TicketDetail>();
                TicketDetail createTicketDetail = new TicketDetail
                {
                    UserID = UserID,
                    Date = DateTime.Now,
                    Message = TicketMessage
                };
                createTicket.TicketDetails.Add(createTicketDetail);
                _ = db.Tickets.Add(createTicket);
                _ = db.SaveChanges();
                return Json(new { IsOk = true });
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return Json(HttpStatusCode.BadRequest, JsonRequestBehavior.AllowGet);
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult TicketList()
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                List<TicketList> ticketList = new List<TicketList>();
                List<Ticket> tickets = db.Tickets.ToList();
                foreach (Ticket item in tickets)
                {
                    TicketList ticket = new TicketList
                    {
                        TicketID = item.TicketID,
                        TicketName = item.TicketName,
                        TicketStatus = item.TicketStatusEnumType,
                        LastActivity = item.LastActivity.ToString("HH:mm:ss tt"),
                        Name = db.Users.FirstOrDefault(m => m.UserID == item.UserID).Name,
                        LastName = db.Users.FirstOrDefault(m => m.UserID == item.UserID).SurName,
                        Image = db.Users.FirstOrDefault(m => m.UserID == item.UserID).Image,
                        Email = db.Users.FirstOrDefault(m => m.UserID == item.UserID).Email
                    };
                    ticketList.Add(ticket);
                }
                ticketList = ticketList.OrderBy(m => m.TicketStatus == TICKETSTATUS.AwaitingAnswer).ToList();
                return View(ticketList);
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "BadRequest");
            }
        }

        [Authorize(Roles = "Admin")]
        public ActionResult TicketChatAdmin(int? id)
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                Ticket ticket = db.Tickets.FirstOrDefault(m => m.TicketID == id);
                if(ticket == null)
                {
                    return View(new Ticket());
                }
                else
                {
                    return View(ticket);
                }
             
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, "BadRequest");
            }
        }

        [HttpGet]
        public JsonResult TicketChatAdminn()
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                List<Ticket> tickets = db.Tickets.Where(m => m.TicketStatusEnumType != TICKETSTATUS.Closed).ToList();
                foreach (Ticket item in tickets)
                {
                    item.TicketDetails = item.TicketDetails.OrderBy(m => m.Date).ToList();
                }
                tickets = tickets.OrderBy(m => m.TicketStatusEnumType == TICKETSTATUS.Answered).ToList();

                return Json(tickets.Select(x => new
                {
                    x.TicketID,
                    x.TicketName,
                    x.CreateDate,
                    LastActivity = x.LastActivity.ToString("HH:mm:ss tt"),
                    x.TicketStatusEnumType,
                    TicketDetail = x.TicketDetails.Select(y => new
                    {
                        y.Message,
                        y.Date,
                        UserRole = y.User.Role,
                    })
                }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return Json(HttpStatusCode.BadRequest, JsonRequestBehavior.AllowGet);

            }
        
        }

        [Authorize(Roles = "Member")]
        public ActionResult TicketChatMember()
        {
            return View();
        }

        [HttpGet]
        public JsonResult TicketChatMemmber()
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                int UserID = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                List<Ticket> tickets = db.Tickets.Where(m => m.UserID == UserID).ToList();
                foreach (Ticket item in tickets)
                {
                    item.TicketDetails = item.TicketDetails.OrderBy(m => m.Date).ToList();
                }
                tickets = tickets.OrderBy(m => m.TicketStatusEnumType == TICKETSTATUS.Closed)
                .ThenBy(m => m.TicketStatusEnumType == TICKETSTATUS.Answered).ToList();
                return Json(tickets.Select(x => new
                {
                    x.TicketID,
                    x.TicketName,
                    x.CreateDate,
                    LastActivity = x.LastActivity.ToString("HH:mm:ss tt"),
                    x.TicketStatusEnumType,
                    TicketDetail = x.TicketDetails.Select(y => new
                    {
                        y.Message,
                        y.Date,
                        UserRole = y.User.Role,
                    })
                }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return Json(HttpStatusCode.BadRequest, JsonRequestBehavior.AllowGet);
            }
        
        }

        [HttpGet]
        public JsonResult TicketChat(int? id)
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                List<Ticket> ticketChat = db.Tickets.Where(m => m.TicketID == id).ToList();
                string userIdenttyRole = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).Role;
                return Json(ticketChat.Select(x => new
                {
                    userIdenttyRole,
                    LastActivity = x.LastActivity.ToString("HH:mm:ss tt"),
                    x.TicketStatusEnumType,
                    TicketDetail = x.TicketDetails.Select(y => new
                    {
                        TicketDetailID = y.TicketDetayID,
                        y.Message,
                        y.Date,
                        UserRole = y.User.Role
                    })
                }), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                Logger.GetLogger().LogError(LOGTYPE.ERROR, ex.Data.ToString(), ex.Message, ex.StackTrace);
                return Json(HttpStatusCode.BadRequest, JsonRequestBehavior.AllowGet);
            }
     
        }

        [HttpPost]
        public JsonResult MessageButton(int TicketID, string Message)
        {
            try
            {
                int UserId = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name).UserID;
                Logger.GetLogger().LogUser(LOGTYPE.INFO, UserId);
                User user = db.Users.FirstOrDefault(m => m.Email == User.Identity.Name);
                Ticket ticket = db.Tickets.FirstOrDefault(m => m.TicketID == TicketID);
                if (ticket.TicketStatusEnumType != TICKETSTATUS.Closed)
                {
                    ticket.TicketStatusEnumType = user.Role == "Admin" ? TICKETSTATUS.Answered : TICKETSTATUS.AwaitingAnswer;
                    TicketDetail ticketDetail = new TicketDetail

MMakerBotPanel/Views/Ticket/CreateTicket.cshtml
@model MMakerBotPanel.Database.Model.Ticket

@{
    ViewBag.Title = "CreateTicket";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>CreateTicket</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Ticket</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.TicketName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketText, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TicketText, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TicketText, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CreateDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastActivity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastActivity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastActivity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TicketStatusEnumType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.TicketStatusEnumType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TicketStatusEnumType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserID, "UserID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MMakerBotPanel/Views/Ticket/TicketList.cshtml
@model IEnumerable<MMakerBotPanel.Models.TicketList>

@{
    Layout = "~/Views/Shared/_Admin_Layout.cshtml";
}

<!-- BEGIN PAGE LEVEL CUSTOM STYLES -->
<link rel="stylesheet" type="text/css" href="~/Content/light/plugins/table/datatable/datatables.css">
<link rel="stylesheet" type="text/css" href="~/Content/light/assets/css/forms/theme-checkbox-radio.css">
<link rel="stylesheet" type="text/css" href="~/Content/light/plugins/table/datatable/dt-global_style.css">
<link rel="stylesheet" type="text/css" href="~/Content/light/plugins/table/datatable/custom_dt_custom.css">
<!-- END PAGE LEVEL CUSTOM STYLES -->

<div id="content" class="main-content">
    <div class="layout-px-spacing">

        <div class="row layout-spacing">
            <div class="col-lg-12" style="margin-top:2rem">
                <div class="statbox widget box box-shadow">
                    <div class="widget-content widget-content-area">
                        <div class="table-responsive mb-4">
                            <table id="style-3" class="table style-3  table-hover">
                                <thead>
                                    <tr>
                                        <th class="checkbox-column text-center">Ticket ID </th>
                                        <th class="text-center">Image</th>
                                        <th>Name</th>
                                        <th>Last Activity</th>
                                        <th>Ticket Name</th>
                                        <th class="text-center">Ticket Status</th>
                                        <th class="text-center">Chat</th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td class="checkbox-column text-center">@item.TicketID </td>
                                            <td class="text-center">
                                                <span><img src="data:image/png;base64,@item.Image" class="profile-img" alt="avatar"></span>
                                            </td>
                                            <td>@item.Name</td>
                                            <td>@item.LastActivity</td>
                                            <td style=" overflow: hidden; text-overflow: ellipsis; white-space: nowrap;">@item.TicketName</td>
                                            <td class="text-center"><span class="badge badge-danger">@item.TicketStatus</span></td>
                                            <td class="text-center">
                                                <ul class="table-controls">
                                                    <li><a href="@Url.Action("TicketChatAdmin" , "Ticket" , new {id = item.TicketID})" class="bs-tooltip" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-edit-2 p-1 br-6 mb-1"><path d="M17 3a2.828 2.828 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5L17 3z"></path></svg></a></li>
                                                </ul>
                                            </td>
                                        </tr>
                                    }

                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

<!-- BEGIN PAGE LEVEL SCRIPTS -->
<script src="~/Content/light/plugins/table/datatable/datatables.js"></script>
<script>
    // var e;

    c3 = $('#style-3').DataTable({
        "oLanguage": {
            "oPaginate": { "sPrevious": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-left"><line x1="19" y1="12" x2="5" y2="12"></line><polyline points="12 19 5 12 12 5"></polyline></svg>', "sNext": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-arrow-right"><line x1="5" y1="12" x2="19" y2="12"></line><polyline points="12 5 19 12 12 19"></polyline></svg>' },
            "sInfo": "Showing page _PAGE_ of _PAGES_",
            "sSearch": '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-search"><circle cx="11" cy="11" r="8"></circle><line x1="21" y1="21" x2="16.65" y2="16.65"></line></svg>',
            "sSearchPlaceholder": "Search...",
            "sLengthMenu": "Results :  _MENU_",
        },
        "stripeClasses": [],
        "lengthMenu": [5, 10, 20, 50],
        "pageLength": 5
    });

    multiCheck(c3);

</script>
<!-- END PAGE LEVEL SCRIPTS -->  